# Generated by Django 3.1.5 on 2021-07-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=40)),
                ('member_id', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
    ]
