# Generated by Django 3.1.5 on 2021-07-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='member_name',
            new_name='name',
        ),
    ]
