# Generated by Django 3.1.5 on 2021-07-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210726_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='member_name',
        ),
    ]
