# Generated by Django 3.1.5 on 2021-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210726_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='overdue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_id',
            field=models.IntegerField(null=True),
        ),
    ]
