# Generated by Django 3.1.5 on 2021-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210726_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_id',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
