# Generated by Django 3.1.5 on 2021-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210726_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='overdue',
            field=models.IntegerField(default=0),
        ),
    ]
