# Generated by Django 3.1.5 on 2021-08-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceReserve',
        ),
    ]
