# Generated by Django 3.1.5 on 2021-08-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210726_2224'),
        ('rental', '0002_delete_devicereserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReserve',
            fields=[
                ('device_reserve_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('device_reserve_date', models.DateField()),
                ('device_due_date', models.DateField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dReserve_id', to='rental.rentaldevice')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dReserve_id', to='account.user')),
            ],
        ),
    ]
