# Generated by Django 3.1.5 on 2021-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_devicereserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereserve',
            name='device_reserve_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
