# Generated by Django 3.1.5 on 2021-08-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210726_2224'),
        ('rental', '0004_auto_20210803_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicereserve',
            options={'ordering': ['device_reserve_id']},
        ),
        migrations.CreateModel(
            name='GameReserve',
            fields=[
                ('game_reserve_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('game_reserve_date', models.DateField(auto_now_add=True)),
                ('game_due_date', models.DateField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gReserve_id', to='rental.rentaldevice')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gReserve_id', to='account.user')),
            ],
            options={
                'ordering': ['game_reserve_id'],
            },
        ),
    ]
