# Generated by Django 3.1.5 on 2021-08-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20210806_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereserve',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gReserve_id', to='rental.rentalgame'),
        ),
    ]
