# Generated by Django 3.1.5 on 2021-08-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210726_2224'),
        ('rental', '0006_auto_20210807_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalgame',
            options={'ordering': ['game_id', '-device_value', '-genre']},
        ),
        migrations.AddField(
            model_name='devicerental',
            name='dreturn_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gamerental',
            name='greturn_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='devicereserve',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dReserve_d_id', to='rental.rentaldevice'),
        ),
        migrations.AlterField(
            model_name='devicereserve',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dReserve_m_id', to='account.user'),
        ),
        migrations.AlterField(
            model_name='gamereserve',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gReserve_g_id', to='rental.rentalgame'),
        ),
        migrations.AlterField(
            model_name='gamereserve',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gReserve_m_id', to='account.user'),
        ),
    ]
