# Generated by Django 3.1.5 on 2021-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_auto_20210807_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentaldevice',
            options={'ordering': ['device_id']},
        ),
        migrations.AlterField(
            model_name='devicerental',
            name='overdue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamerental',
            name='overdue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
