# Generated by Django 3.1.5 on 2021-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210920_0327'),
        ('rental', '0008_auto_20210920_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaldevice',
            name='device_like',
            field=models.ManyToManyField(blank=True, related_name='device_like', to='account.User'),
        ),
    ]
