# Generated by Django 3.1.5 on 2021-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210920_0327'),
        ('rental', '0009_rentaldevice_device_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgame',
            name='game_like',
            field=models.ManyToManyField(blank=True, related_name='game_like', to='account.User'),
        ),
    ]
