# Generated by Django 3.1.5 on 2021-10-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rentalgame_game_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaldevice',
            name='platform',
        ),
        migrations.AddField(
            model_name='devicevalues',
            name='platform',
            field=models.CharField(choices=[('PS', 'PlayStaion'), ('ND', 'Nintendo')], max_length=2, null=True),
        ),
    ]
