# Generated by Django 3.1.5 on 2021-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_auto_20211001_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalgame',
            name='game_video',
            field=models.URLField(null=True),
        ),
    ]
