# Generated by Django 3.1.5 on 2021-09-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210920_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='p_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_type', to='board.posttype'),
        ),
    ]
